import { motion } from "framer-motion";
import { useTheme } from "@/context/ThemeContext";
import { cn } from "@/lib/utils";
import PlexusTerrainBackground from "@/components/landing/PlexusTerrainBackground";
import GradientOrbs from "@/components/motion/GradientOrbs";
import Reveal from "@/components/motion/Reveal";
import SpotlightCard from "@/components/motion/SpotlightCard";
import PageHero from "@/components/motion/PageHero";
import ScrollProgress from "@/components/motion/ScrollProgress";
import BackToTop from "@/components/motion/BackToTop";
import { glassCard } from "@/components/motion/styles";
import { FileText, CheckCircle, AlertTriangle, Ban, Scale, Mail } from "lucide-react";

const sections = [
  {
    icon: CheckCircle,
    title: "Acceptance of Terms",
    accent: "text-emerald-500",
    content: `By accessing or using Repo Verify ("the Service"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service. We reserve the right to update these terms at any time — continued use after changes constitutes acceptance.`,
  },
  {
    icon: FileText,
    title: "Use of the Service",
    accent: "text-cyan-500",
    content: `Repo Verify is an AI-powered code analysis platform. You may use the Service to:

• Analyze public and private GitHub repositories
• Generate code reviews, documentation, and architecture diagrams
• Chat with an AI assistant about your codebase
• Export analysis reports and documentation

You agree NOT to:
• Use the Service for any illegal purpose or in violation of any laws
• Attempt to reverse-engineer, decompile, or extract the underlying AI models
• Upload malicious code, malware, or exploit material
• Exceed rate limits or abuse the API without authorization
• Resell or redistribute the Service without written permission`,
  },
  {
    icon: AlertTriangle,
    title: "AI-Generated Content",
    accent: "text-amber-500",
    content: `All code reviews, documentation, analysis, and chat responses are generated by AI models and are provided "as is." While we strive for accuracy, AI-generated content may contain errors, hallucinations, or inaccuracies.

You are responsible for:
• Reviewing all AI-generated suggestions before applying them to production code
• Verifying the accuracy of documentation and analysis
• Not relying solely on AI output for security-critical decisions

AI-generated content should be treated as a starting point for human review, not a final deliverable.`,
  },
  {
    icon: Ban,
    title: "No Warranty Disclaimer",
    accent: "text-rose-500",
    content: `THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.

We do not warrant that the Service will be uninterrupted, error-free, or free of viruses or other harmful components. We are not responsible for any data loss, code corruption, or damages resulting from use of AI-generated suggestions.`,
  },
  {
    icon: Scale,
    title: "Limitation of Liability",
    accent: "text-violet-500",
    content: `TO THE MAXIMUM EXTENT PERMITTED BY LAW, REPO VERIFY AND ITS AFFILIATES SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, DATA, OR BUSINESS OPPORTUNITIES, ARISING FROM USE OF THE SERVICE.

Our total liability shall not exceed the amount you paid us in the 12 months preceding the claim, or $100, whichever is greater.`,
  },
];

export default function TermsPage() {
  const { theme } = useTheme();
  const isDark = theme === "dark";

  return (
    <motion.main
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      transition={{ duration: 0.4 }}
      className={cn("min-h-screen font-[Inter] transition-colors duration-300", isDark ? "bg-[#07030F] text-white" : "bg-white text-slate-900")}
    >
      <PlexusTerrainBackground />
      <GradientOrbs />
      <ScrollProgress className="bg-gradient-to-r from-slate-400 via-violet-500 to-fuchsia-500" />

      <div className="relative z-10 mx-auto max-w-4xl px-4 py-12 sm:px-6 sm:py-16 md:py-20">
        <PageHero
          icon={FileText}
          label="Terms of Service"
          badgeClass={isDark ? "border-fuchsia-500/20 bg-fuchsia-500/10 text-fuchsia-300" : "border-fuchsia-200 bg-fuchsia-100 text-fuchsia-700"}
          titleBefore={["Terms", "of"]}
          gradientWord="Service"
          subtitle="Effective June 2026. Please read carefully before using Repo Verify."
          gradientClass="from-slate-400 via-violet-400 to-fuchsia-400"
          glowClass="rgba(168, 85, 247, 0.12)"
        />

        <div className="space-y-10">
          {sections.map((section, si) => {
            const Icon = section.icon;
            return (
              <Reveal key={section.title} delay={si * 0.05} y={32}>
                <SpotlightCard
                  spotlightColor={isDark ? "rgba(168, 85, 247, 0.1)" : "rgba(168, 85, 247, 0.08)"}
                  className={cn("rounded-2xl border transition-shadow duration-300", glassCard(isDark), isDark ? "hover:shadow-xl hover:shadow-fuchsia-500/10" : "hover:shadow-xl hover:shadow-slate-200/60")}
                  innerClassName="p-6 sm:p-8"
                >
                  <motion.div
                    initial={{ scaleX: 0 }}
                    whileInView={{ scaleX: 1 }}
                    viewport={{ once: true }}
                    transition={{ delay: 0.15, duration: 0.9, ease: "easeOut" }}
                    className="absolute inset-x-6 top-0 h-[2px] origin-left rounded-full bg-gradient-to-r from-violet-500 via-fuchsia-500 to-pink-500"
                  />

                  <div className="mb-4 flex items-center gap-3">
                    <motion.div
                      whileHover={{ rotate: 10, scale: 1.1 }}
                      transition={{ type: "spring", stiffness: 350, damping: 14 }}
                      className={cn("flex h-11 w-11 items-center justify-center rounded-xl border", isDark ? "border-fuchsia-500/20 bg-fuchsia-500/10" : "border-fuchsia-200 bg-fuchsia-100")}
                    >
                      <Icon size={20} className={section.accent} />
                    </motion.div>
                    <h2 className="font-[Outfit] text-xl font-bold">{section.title}</h2>
                  </div>

                  <div className={cn("whitespace-pre-line rounded-xl border p-5 text-sm leading-relaxed", isDark ? "border-white/[0.06] bg-white/[0.02] text-slate-400" : "border-slate-200/70 bg-white/50 text-slate-500")}>
                    {section.content}
                  </div>
                </SpotlightCard>
              </Reveal>
            );
          })}
        </div>

        <Reveal delay={0.1} className="mt-12">
          <motion.div
            whileHover={{ y: -3 }}
            transition={{ type: "spring", stiffness: 300, damping: 22 }}
            className={cn("flex flex-col items-center justify-center gap-3 rounded-2xl border p-8 text-center sm:flex-row sm:gap-4", glassCard(isDark))}
          >
            <motion.span
              animate={{ y: [0, -5, 0] }}
              transition={{ repeat: Infinity, duration: 2.6, ease: "easeInOut" }}
              className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-gradient-to-br from-violet-500 to-fuchsia-600 text-white shadow-lg shadow-violet-500/20"
            >
              <Mail size={20} />
            </motion.span>
            <p className={cn("text-sm", isDark ? "text-slate-400" : "text-slate-500")}>
              Questions about these terms? Contact us at{" "}
              <a href="mailto:legal@repo-verify.dev" className="font-medium text-violet-500 transition-colors hover:text-violet-400">
                legal@repo-verify.dev
              </a>
            </p>
          </motion.div>
        </Reveal>
      </div>

      <BackToTop />
    </motion.main>
  );
}
