import { Link } from "react-router-dom";
import { motion } from "framer-motion";
import { useTheme } from "@/context/ThemeContext";
import { ArrowLeft, FileText, AlertTriangle, CheckCircle, Ban, Scale } from "lucide-react";

const pageVariants = {
  hidden: { opacity: 0 },
  visible: { opacity: 1, transition: { duration: 0.4, staggerChildren: 0.08 } },
};

const itemVariants = {
  hidden: { opacity: 0, y: 30 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.5, ease: [0.22, 1, 0.36, 1] as const } },
};

const badgeVariants = {
  hidden: { opacity: 0, scale: 0.7 },
  visible: { opacity: 1, scale: 1, transition: { type: "spring" as const, stiffness: 260, damping: 18 } },
};

const sections = [
  {
    icon: CheckCircle,
    title: "Acceptance of Terms",
    content: `By accessing or using Repo Verify ("the Service"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service. We reserve the right to update these terms at any time — continued use after changes constitutes acceptance.`,
  },
  {
    icon: FileText,
    title: "Use of the Service",
    content: `Repo Verify is an AI-powered code analysis platform. You may use the Service to:

• Analyze public and private GitHub repositories
• Generate code reviews, documentation, and architecture diagrams
• Chat with an AI assistant about your codebase
• Export analysis reports and documentation

You agree NOT to:
• Use the Service for any illegal purpose or in violation of any laws
• Attempt to reverse-engineer, decompile, or extract the underlying AI models
• Upload malicious code, malware, or exploit material
• Exceed rate limits or abuse the API without authorization
• Resell or redistribute the Service without written permission`,
  },
  {
    icon: AlertTriangle,
    title: "AI-Generated Content",
    content: `All code reviews, documentation, analysis, and chat responses are generated by AI models and are provided "as is." While we strive for accuracy, AI-generated content may contain errors, hallucinations, or inaccuracies.

You are responsible for:
• Reviewing all AI-generated suggestions before applying them to production code
• Verifying the accuracy of documentation and analysis
• Not relying solely on AI output for security-critical decisions

AI-generated content should be treated as a starting point for human review, not a final deliverable.`,
  },
  {
    icon: Ban,
    title: "No Warranty Disclaimer",
    content: `THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.

We do not warrant that the Service will be uninterrupted, error-free, or free of viruses or other harmful components. We are not responsible for any data loss, code corruption, or damages resulting from use of AI-generated suggestions.`,
  },
  {
    icon: Scale,
    title: "Limitation of Liability",
    content: `TO THE MAXIMUM EXTENT PERMITTED BY LAW, REPO VERIFY AND ITS AFFILIATES SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, DATA, OR BUSINESS OPPORTUNITIES, ARISING FROM USE OF THE SERVICE.

Our total liability shall not exceed the amount you paid us in the 12 months preceding the claim, or $100, whichever is greater.`,
  },
];

export default function TermsPage() {
  const { theme } = useTheme();
  const isDark = theme === "dark";

  return (
    <motion.main
      variants={pageVariants}
      initial="hidden"
      animate="visible"
      className={`min-h-screen font-[Inter] transition-colors duration-300 ${isDark ? "bg-[#07030F] text-white" : "bg-white text-slate-900"}`}
    >
      <div className="fixed inset-0 pointer-events-none overflow-hidden">
        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[700px] h-[700px] bg-slate-600/4 rounded-full blur-[150px]" />
        <motion.div
          animate={{ y: [0, -24, 0], x: [0, 10, 0] }}
          transition={{ repeat: Infinity, duration: 10, ease: "easeInOut" }}
          className="absolute top-32 left-[18%] h-56 w-56 rounded-full bg-slate-500/[0.04] blur-[90px]"
        />
        <motion.div
          animate={{ y: [0, 16, 0], x: [0, -12, 0] }}
          transition={{ repeat: Infinity, duration: 8, ease: "easeInOut" }}
          className="absolute bottom-36 right-[20%] h-40 w-40 rounded-full bg-violet-500/[0.04] blur-[70px]"
        />
      </div>

      <div className="relative z-10 mx-auto max-w-4xl px-4 py-12 sm:px-6 sm:py-16 md:py-20">
        <motion.div variants={itemVariants} className="mb-10">
          <Link to="/" className={`inline-flex items-center gap-2 text-sm font-medium transition-colors ${isDark ? "text-slate-400 hover:text-white" : "text-slate-500 hover:text-slate-900"}`}>
            <ArrowLeft size={16} /> Back to Home
          </Link>
        </motion.div>

        <motion.div variants={itemVariants} className="mb-14 text-center">
          <motion.div variants={badgeVariants} className={`mb-5 inline-flex items-center gap-2 rounded-full border px-4 py-1.5 text-sm font-medium ${isDark ? "border-slate-400/20 bg-slate-400/10 text-slate-300" : "border-slate-200 bg-slate-100 text-slate-600"}`}>
            <FileText size={14} className="text-slate-400" /> Terms of Service
          </motion.div>
          <h1 className="font-[Outfit] text-3xl font-extrabold tracking-tight sm:text-4xl md:text-5xl">
            Terms of{" "}
            <span className="bg-gradient-to-r from-slate-400 via-violet-400 to-fuchsia-400 bg-clip-text text-transparent animate-[shimmer_3s_ease-in-out_infinite] bg-[length:200%_auto]">Service</span>
          </h1>
          <p className={`mx-auto mt-5 max-w-xl text-lg ${isDark ? "text-slate-400" : "text-slate-500"}`}>
            Effective June 2026. Please read carefully before using Repo Verify.
          </p>
        </motion.div>

        <motion.div variants={pageVariants} className="space-y-10">
          {sections.map((section) => {
            const Icon = section.icon;
            return (
              <motion.div
                key={section.title}
                variants={itemVariants}
                whileHover={{ y: -2 }}
                transition={{ type: "spring" as const, stiffness: 300, damping: 25 }}
                className={`rounded-2xl border p-6 sm:p-8 transition-shadow duration-300 ${isDark ? "border-white/[0.06] bg-white/[0.02] hover:shadow-lg hover:shadow-violet-500/5" : "border-slate-200 bg-white hover:shadow-lg hover:shadow-slate-200/50"}`}
              >
                <div className="flex items-center gap-3 mb-4">
                  <motion.div
                    whileHover={{ rotate: 15, scale: 1.1 }}
                    transition={{ type: "spring" as const, stiffness: 400 }}
                    className={`flex h-9 w-9 items-center justify-center rounded-lg ${isDark ? "bg-violet-500/10" : "bg-violet-100"}`}
                  >
                    <Icon size={18} className="text-violet-500" />
                  </motion.div>
                  <h2 className={`font-[Outfit] text-xl font-bold ${isDark ? "text-white" : "text-slate-900"}`}>{section.title}</h2>
                </div>
                <div className={`rounded-xl border p-5 text-sm leading-relaxed whitespace-pre-line ${isDark ? "border-white/[0.06] bg-white/[0.02] text-slate-400" : "border-slate-200 bg-slate-50 text-slate-500"}`}>
                  {section.content}
                </div>
              </motion.div>
            );
          })}
        </motion.div>

        <motion.div
          variants={itemVariants}
          whileHover={{ y: -2 }}
          transition={{ type: "spring" as const, stiffness: 300, damping: 25 }}
          className={`mt-12 rounded-2xl border p-6 text-center ${isDark ? "border-white/[0.06] bg-white/[0.03]" : "border-slate-200 bg-white"}`}
        >
          <p className={`text-sm ${isDark ? "text-slate-400" : "text-slate-500"}`}>
            Questions about these terms? Contact us at{" "}
            <a href="mailto:legal@repo-verify.dev" className="text-violet-500 hover:text-violet-400 font-medium">legal@repo-verify.dev</a>
          </p>
        </motion.div>
      </div>
    </motion.main>
  );
}
